# ==== CONFIGURE =====
# Use a Node 16 base image
FROM python:3.12.0b3-bookworm

# Set the working directory to /app inside the container
WORKDIR /app
# Copy app files

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .

#CMD [ "python3", "./get_titles_from_disk.py" ]
CMD [ "python3", "./mark_titles_as_watched.py", "-n 6" ]
ENTRYPOINT [ "python3", "./mark_titles_as_watched.py" ]


